name: ADK Answering Agent for Discussions

on:
  discussion:
    types: [created]
  discussion_comment:
    types: [created]

jobs:
  agent-answer-questions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Authenticate to Google Cloud
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.ADK_GCP_SA_KEY }}'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-adk

      - name: Run Answering Script
        env:
          GITHUB_TOKEN: ${{ secrets.ADK_TRIAGE_AGENT }}
          GOOGLE_CLOUD_PROJECT: ${{ secrets.GOOGLE_CLOUD_PROJECT }}
          GOOGLE_CLOUD_LOCATION: ${{ secrets.GOOGLE_CLOUD_LOCATION }}
          VERTEXAI_DATASTORE_ID: ${{ secrets.VERTEXAI_DATASTORE_ID }}
          GOOGLE_GENAI_USE_VERTEXAI: 1
          OWNER: 'google'
          REPO: 'adk-python'
          INTERACTIVE: 0
          DISCUSSION_NUMBER: ${{ github.event.discussion.number }}
          PYTHONPATH: contributing/samples
        run: python -m adk_answering_agent.main
